[package]
name = "weather_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
serde_json = "1.0.128"
colored = "2.1.0"
